contents:
  repositories:
    - https://packages.wolfi.dev/os
    - https://alauda-mesh.github.io/istio-base-images
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    - https://alauda-mesh.github.io/istio-base-images/melange.rsa.pub
  packages:
    - wolfi-baselayout
    - alauda-baselayout
    - ca-certificates-bundle
    - tzdata
    - kiali=2.11.0@local

entrypoint:
  command: /opt/kiali/kiali

work-dir: /opt/kiali

archs:
  - x86_64
  - aarch64

environment:
  KIALI_HOME: /opt/kiali
  PATH: /opt/kiali:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin
