package:
  name: kiali-2.17
  version: "2.17.1"
  epoch: 0
  description: The Console for Istio Service Mesh
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates
    provides:
      - kiali=${{package.full-version}}

environment:
  contents:
    packages:
      - automake
      - busybox
      - ca-certificates-bundle
      - go
      - make
      - nodejs
      - npm
      - tree
      - yarn

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/alauda-mesh/kiali
      branch: kiali-2.17.1

  - runs: |
      echo "Kiali source branch: kiali-2.17.1"
      echo "Kiali source commit: $(git rev-parse HEAD)"
      git log -1 --format='Kiali source commit details: %H %cI %s'

  - runs: make clean-all build-ui

  - uses: go/build # Builds to /opt/kiali/kiali
    with:
      packages: .
      prefix: opt
      install-dir: kiali
      output: kiali
      ldflags: |
        -X github.com/kiali/kiali/cmd.version=v${{package.version}} \
        -X github.com/kiali/kiali/cmd.commitHash=$(git rev-parse HEAD)

  - uses: strip

test:
  pipeline:
    - name: Verify Kiali API
      runs: |
        # Check if binary runs
        /opt/kiali/kiali --help

update:
  enabled: true
  github:
    identifier: kiali/kiali
    strip-prefix: v
