package:
  name: kiali-2.11
  version: "2.11.0"
  epoch: 1
  description: The Console for Istio Service Mesh
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates
    provides:
      - kiali=${{package.full-version}}

environment:
  contents:
    packages:
      - automake
      - busybox
      - ca-certificates-bundle
      - go
      - nodejs
      - npm
      - tree
      - yarn

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kiali/kiali
      tag: v${{package.version}}
      expected-commit: 5b9347708ad5e28800528fcdc333700c15d9bd54

  - uses: go/bump
    with:
      deps: |-
        golang.org/x/oauth2@v0.27.0
        golang.org/x/crypto@v0.35.0
        golang.org/x/net@v0.38.0

  - runs: make clean-all build-ui

  - uses: go/build # Builds to /opt/kiali/kiali
    with:
      packages: .
      prefix: opt
      install-dir: kiali
      output: kiali
      ldflags: |
        -X runtime.buildVersion=unknown \
        -X runtime.modinfo= \
        -X main.version=v${{package.version}} \
        -X main.commitHash=$(git rev-parse HEAD) \
        -X main.goVersion=unknown

  - uses: strip

test:
  pipeline:
    - name: Verify Kiali API
      runs: |
        # Check if binary runs
        /opt/kiali/kiali --help

update:
  enabled: true
  github:
    identifier: kiali/kiali
    strip-prefix: v
