name: Build Ansible Operator

on:
  pull_request:
    paths:
      - ".github/workflows/build-ansible-operator.yaml"
      - "ansible-operator/**"
      - "docker/ansible-operator/**"
  workflow_dispatch:
    inputs:
      epoch:
        description: Release epoch
        required: true
        type: number
        default: 0

jobs:
  build-image:
    name: Build ansible-operator image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine ansible-operator image-version
        id: image-version
        run: |
          # Search docker/ansible-operator/Dockerfile, the version in pattern "ARG ANSIBLE_OPERATOR_VERSION=..."
          VERSION=$(cat docker/ansible-operator/Dockerfile | grep "^ARG ANSIBLE_OPERATOR_VERSION=" | cut -d "=" -f 2)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build ansible-operator image
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v4
        with:
          context: docker/ansible-operator
          file: docker/ansible-operator/Dockerfile
          push: false

      - name: Build and push ansible-operator image
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v4
        with:
          context: docker/ansible-operator
          file: docker/ansible-operator/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/ansible-operator:$${{ steps.image-version.outputs.version }}-r${{ inputs.epoch }}
